### ISSUE TITLE
Remove Graham Edgecombe Monitor

### ISSUE THREAD

**Issue by rmhrisk** [google/certificate-transparency-community-site#32]
Graham Edgecombe has taken down his monitor. We should remove it from https://certificate.transparency.dev/monitors/

**Comment by naumanshah03** [comment]
@rmhrisk supposedly it has been removed now
You can close this ticket

**Comment by roger2hk** [comment]
Fixed in https://github.com/google/certificate-transparency-community-site/commit/9b634a0fd819697a65fdd8c6626ebf42a6bcae0b.
