### ISSUE TITLE
current_log_list API failing on https://certificate.transparency.dev/

### ISSUE THREAD

**Issue by naumanshah03** [google/certificate-transparency-community-site#38]
On the following page https://certificate.transparency.dev/logs/, one of the APIs is failing because of which the all usable logs list is failing to load.
It is failing due to a CORS error and the API in question is https://valid.apple.com/ct/log_list/current_log_list.json

![image](https://user-images.githubusercontent.com/22236992/177142514-07f17d7f-3bcb-41db-b311-b55aa477d3b4.png)

Please check this issue.

**Comment by naumanshah03** [comment]
Response header as requested by @roger2hk 
`HTTP/1.1 200 OK
x-amz-id-2: oKjePZqeCXeaAbzXMZ4vTg3GIKOKMl8ig3YXDaQYpN0V/Qpn71xwkZdDPPAxPx/IuyuBuHvrXTs=
x-amz-request-id: 3H1BP40TR7TTQVS6
Last-Modified: Mon, 02 May 2022 22:35:45 GMT
ETag: "64cecfaf047781b79c5f8d7e224fd31a"
Accept-Ranges: bytes
Content-Type: application/json
Server: AmazonS3
Vary: Accept-Encoding
Content-Encoding: gzip
Date: Tue, 05 Jul 2022 06:55:14 GMT
Content-Length: 10143
Connection: keep-alive
`

![image](https://user-images.githubusercontent.com/22236992/177268386-e5964660-fcae-4190-9e31-77f0c911b687.png)
Let me know if HAR file is needed for further investigation

Regards,
Nauman Shah

**Comment by roger2hk** [comment]
I have been trying to replicate the issue but no luck. If it still doesn't work for you, the HAR file would definitely help. The `access-control-allow-origin: *` and CDN information are missing in your response header.

On top of the HAR file, which browser and version are you using?

**Comment by naumanshah03** [comment]
Using Google Chrome Version 103.0.5060.114
Response header didn't have the `access-control-allow-origin` header. Not sure about the CDM information

Attaching the requested HAR taken just now
[certificate.transparency.dev.zip](https://github.com/google/certificate-transparency-community-site/files/9090256/certificate.transparency.dev.zip)

**Comment by roger2hk** [comment]
I could not replicate this issue in other browsers or devices. Please try to browse the same website in other browsers or devices. If it works, there might be some issue with your existing browser settings or extensions.

**Comment by naumanshah03** [comment]
I tried with Mozilla Firefox even with private browsing, Google Chrome with incognito with no extensions enabled, Chrome Canary with incognito with no extension enabled and in all cases it was leading to the same issue.

Could it be an issue with a particular region? or the Apple API being called has some issue?

**Comment by roger2hk** [comment]
Good point. I can replicate this issue using the India proxy. Next step is to get someone from Apple to look into this.

**Comment by naumanshah03** [comment]
Now the issue is resolved.
Please close the ticket

**Comment by roger2hk** [comment]
Great, thanks for the verification.

**Comment by roger2hk** [comment]
The same CORS issue comes back.

**Comment by roger2hk** [comment]
This issue is fixed by Apple and verified.
