### ISSUE TITLE
Sign All Known Logs List

### ISSUE THREAD

**Issue by ecnepsnai** [google/certificate-transparency-community-site#47]
Hello, is there a reason why only the current log list is signed, but the list of all logs is not signed? https://github.com/google/certificate-transparency-community-site/blob/master/docs/google/known-logs.md

Could this be updated so that both are signed? 

For my use case I wish to have historical logs, but I would like to be able to verify the signature as well.

**Comment by carlosjoan91** [comment]
Thanks for reporting this. A signature for all_logs_list.json already exists at https://www.gstatic.com/ct/log_list/v3/all_logs_list.sig (and the corresponding zip file with the .json and .sig files at https://www.gstatic.com/ct/log_list/v3/all_logs_list.zip), but it was not documented in known-logs.md. I sent #48 to add a note about these files.
