### ISSUE TITLE
Unify height of event cards

### ISSUE THREAD

**Issue by ahmed0saber** [google/certificate-transparency-community-site#66]
Event cards in event-grid looks like:
![Annotation 2024-03-15 011421](https://github.com/google/certificate-transparency-community-site/assets/64714761/caa907e7-3535-423a-bdd2-c05367bf5633)

What about unifying their height to look like:
![Annotation 2024-03-15 012217](https://github.com/google/certificate-transparency-community-site/assets/64714761/ec41ad66-52e2-4534-ba6e-49eabf3b718d)

**Comment by roger2hk** [comment]
The new layout looks good to me. Thanks.
